### ISSUE TITLE
There are some websocket closing errors after connecting 

### ISSUE THREAD

**Issue by lugy-bupt** [pion/ion-app-web#109]
### Your environment.
  - Version: Ion server from docker-compose, and ion-app-web from *npm start*
  - Browser: Chrome 92.0.4515.159

### What happened?
Change the ion-app-web package.json with host IP to access the web server from another PC, just like below bold code.

```javascript
  "scripts": {
    "build": "webpack --mode=production --config webpack.config.js --env.production",
    **"start": "webpack-dev-server --config ./webpack.config.js --mode development --open --http --host 10.184.102.183",**
    "start_https": "webpack-dev-server --config ./webpack.config.js --mode development --open --https --cert ./configs/certs/cert.pem --key  ./configs/certs/key.pem"
  },
```

And then open the chrome, access the ion-app-web server with *http://10.184.102.183:8080/*
1. The ion-app-web cannot see the video of other peers.
2. Open the developer tool of chrome, there are lots of websocket errors, like the screen snapshot.

![屏幕截图 2021-08-27 160648](https://user-images.githubusercontent.com/10431855/131096018-2cd66956-3160-42f6-8821-3f03f1d8cb40.png)

**Comment by nntwelve** [comment]
I got the same problem, is there anyone solved this??.
 I found some error in ion server : ```
app-biz_1  | time="2021-09-20 07:07:54.544" msg="BizServer.Singal server stream.Recv() err: EOF"```

**Comment by nntwelve** [comment]
And a count this singal log, I always throw error after 20 times.

```app-biz_1  | time="2021-09-20 07:18:02.786" msg="
app-biz_1  | ----------------signal-----------------
app-biz_1  | room: 61483565726bed00137b01a9
app-biz_1  | peers: 2```

**Comment by nntwelve** [comment]
![image](https://user-images.githubusercontent.com/90548438/133968009-6dbfa8b1-7b5d-42eb-b49c-5945019fb0ac.png)

**Comment by RobinKamps** [comment]
getting the same error with a fresh install of the latest docker ion and ion-app-web...
on localhost / windows without changing the host.

**Comment by RobinKamps** [comment]
resolved the issue by removing the nat1to1 and icelite docker sfu config
