### ISSUE TITLE
Unknown Service.Method /bin.Biz/Signal

### ISSUE THREAD

**Issue by enm10k** [pion/ion-app-web#118]
### Your environment.
  - Version
    - pion/ion-app-web: c7e9f9
    - pion/ion: dcf4f1a
  - Browser: 95.0.4638.69（Official Build） （x86_64）
  - Other Information - N/A

### What did you do?

1. clone pion/ion repo and execute `docker-compose up`
2. clone pion/ion-app-web repo and execute `npm i && npm start`
3. Open http://localhost:8080
4. Enter `Room Id` and `Display Name` then click `Join`

### What did you expect?

Expected to join the room.

### What happened?

Failed to join the room.
As I checked Chrome DevTools, Signal failed with the following error message.

> Unknown Service.Method /bin.Biz/Signal

![スクリーンショット 2021-11-16 15 37 53](https://user-images.githubusercontent.com/17097142/141934758-f5501e42-f523-4db5-adf5-e0916eb081de.png)

**Comment by adwpc** [comment]
pls try new version
