### ISSUE TITLE
invalid volume for caddy data in docker-compose.yml

### ISSUE THREAD

**Issue by schors** [pion/ion-app-web#12]
Caddy data ssl certs included stored inside /data folder. docker-compose.yml provides special named volume for the data "caddy". "/root/.caddy" is mount point for it. Actually "/data" must be. I don't familiar with caddy. But I sure that it's result of caddy version changing.

**Comment by jbrady42** [comment]
Thanks for pointing this out. Looks like it works with both at the moment, but will update that for the future.
