### ISSUE TITLE
TLS Handshake error

### ISSUE THREAD

**Issue by rajababu3** [pion/ion-app-web#27]
2020/06/01 14:27:37 http: TLS handshake error from 197.94.230.123:51063: no certificate available for 'dc-a.ws.proda.gocharting.com'

Why I am getting the above error?

**Comment by al3chen** [comment]
same issue

Attaching to ion-app-web_web_1
web_1  | {"level":"info","ts":1591196332.7908356,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
web_1  | {"level":"info","ts":1591196332.8033297,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["127.0.0.1:2019","localhost:2019","[::1]:2019"]}
web_1  | 2020/06/03 14:58:52 [INFO][cache:0xc00053e370] Started certificate maintenance routine
web_1  | 2020/06/03 14:58:52 [WARNING] Stapling OCSP: no OCSP stapling for [11]: no OCSP server specified in certificate
web_1  | {"level":"info","ts":1591196332.80408,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
web_1  | {"level":"info","ts":1591196332.8126283,"logger":"tls","msg":"setting internal issuer for automation policy that has only internal subjects but no issuer configured","subjects":["localhost"]}
web_1  | {"level":"info","ts":1591196332.8131657,"logger":"tls","msg":"cleaned up storage units"}
web_1  | {"level":"warn","ts":1591196332.8562124,"logger":"pki.ca.local","msg":"installing root certificate (you might be prompted for password)","path":"storage:pki/authorities/local/root.crt"}
web_1  | 2020/06/03 14:58:52 Warning: "certutil" is not available, install "certutil" with "apt install libnss3-tools" or "yum install nss-tools" and try again
web_1  | 2020/06/03 14:58:52 define JAVA_HOME environment variable to use the Java trust
web_1  | 2020/06/03 14:58:52 certificate installed properly in linux trusts
web_1  | {"level":"info","ts":1591196332.8848212,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["localhost"]}
web_1  | 2020/06/03 14:58:52 [WARNING] Stapling OCSP: no OCSP stapling for [localhost]: no OCSP server specified in certificate
web_1  | {"level":"info","ts":1591196332.8855379,"msg":"autosaved config","file":"/config/caddy/autosave.json"}
web_1  | {"level":"info","ts":1591196332.8855507,"msg":"serving initial configuration"}
web_1  | 2020/06/03 14:59:08 http: TLS handshake error from 172.18.0.1:34138: no certificate available for '172.18.0.2'
web_1  | 2020/06/03 14:59:16 http: TLS handshake error from 172.18.0.1:34142: no certificate available for '172.18.0.2'

**Comment by ganadevprajapathy** [comment]
+1. Same issue 
browser.js:21 WebSocket connection to 'wss://localhost:9090/ws?peer=bfb81d21-9fb2-4723-9304-712a4a0be8b4' failed: Error during WebSocket handshake: Unexpected response code: 502

**Comment by jbrady42** [comment]
The first two comments here do no look like errors, if you are not having any trouble accessing the web app. This is the kind of access you should expect when you have a service open to the internet. You will get many requests that are not for your domain. Caddy is just letting you know that an attempt was made to access a domain/site the server is not configured to serve.

**Comment by jbrady42** [comment]
@ganadevprajapathy what you are seeing is related to the biz socket reverse proxy config. Make sure you have the docker services both running on the same hosts and the docker ion network exists.
