### ISSUE TITLE
Unrecognised parameter root

### ISSUE THREAD

**Issue by rajababu3** [pion/ion-app-web#28]
`web_1  | {"level":"info","ts":1591065464.5322976,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
web_1  | run: adapting config using caddyfile: unrecognized parameter name: root`

**Comment by jbrady42** [comment]
This is a valid caddy 2 param.
https://caddyserver.com/docs/caddyfile/directives/root

**Comment by eleomilagrosa** [comment]
@rajababu3 @jbrady42 

did you manage to run it?
I am still having building error

> /var/www/ion-app-web$ sudo docker-compose up --build
Building web
Step 1/14 : FROM node:lts-alpine
 ---> 1c342643aa5c
Step 2/14 : WORKDIR /app
 ---> Using cache
 ---> cc4a62e49bae
Step 3/14 : COPY package.json package-lock.json ./
 ---> Using cache
 ---> e12ee123bdc9
Step 4/14 : RUN npm install
 ---> Using cache
 ---> c55167f77363
Step 5/14 : COPY public/ public/
 ---> Using cache
 ---> 6c23daa027d4
Step 6/14 : COPY src/ src/
 ---> Using cache
 ---> 1946a0575ad3
Step 7/14 : COPY styles/ styles/
 ---> Using cache
 ---> ce3d4b1e1a2f
Step 8/14 : COPY webpack.config.js .babelrc ./
 ---> Using cache
 ---> 855add1bc7a5
Step 9/14 : RUN npm run build
 ---> Using cache
 ---> 5f60e6a66f97

Step 10/14 : FROM caddy:2.0.0-alpine
 ---> 2721e97adcec
Step 11/14 : ENV ENABLE_TELEMETRY="false"
 ---> Using cache
 ---> df5226b07b83
Step 12/14 : WORKDIR /app
 ---> Using cache
 ---> 3406b90f2430
Step 13/14 : COPY configs/certs/ /app/certs/
 ---> Using cache
 ---> 89ff54521017
Step 14/14 : COPY --from=0 /app/dist /app/dist
 ---> Using cache
 ---> 869dd492be56

Successfully built 869dd492be56
Successfully tagged ion-app-web_web:latest
Creating ion-app-web_web_1 ... done
Attaching to ion-app-web_web_1
web_1  | {"level":"info","ts":1592042577.3683295,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
web_1  | run: adapting config using caddyfile: unrecognized parameter name: root
ion-app-web_web_1 exited with code 1
