### ISSUE TITLE
No videos appear on Safari

### ISSUE THREAD

**Issue by ijt** [pion/ion-app-web#30]
### Your environment.
  - Version: d7110cc5fae5d793d78e280d8599c34cbcd623f2
  - Browser: iOS Safari 13

### What did you do?

I started ion and ion-app-web on my vm. It worked fine on Chrome on my Mac.

### What did you expect?
I expected to see my local video and the remote video.

### What happened?

The widgets came up but no videos were visible.

![IMG_0580](https://user-images.githubusercontent.com/15530/83905665-ed440b00-a716-11ea-839d-2b2cd2e6611b.PNG)

**Comment by ijt** [comment]
<img width="1001" alt="Screen Shot 2020-06-05 at 10 57 13 AM" src="https://user-images.githubusercontent.com/15530/83908086-5a599f80-a71b-11ea-9a62-a98fa45d3218.png">

**Comment by ijt** [comment]
I don't understand the error. It says something about `t.publish(this.rid)` at line 8 of `Conference.jsx` but I don't see that there or anywhere in `Conference.jsx` or anywhere in `ion-app-web` or anywhere in `ion`.

**Comment by jbrady42** [comment]
That may be coming from the ion js sdk? @tarrencev

**Comment by ijt** [comment]
@jbrady42 , I'm not seeing any action from the SFU when I connect. Here's a snapshot of the logs:

<img width="1050" alt="Screen Shot 2020-06-05 at 12 56 14 PM" src="https://user-images.githubusercontent.com/15530/83917630-17ec8e80-a72c-11ea-8308-3221c2635473.png">

**Comment by ijt** [comment]
I'm seeing the same issue with Firefox and Chrome on iOS.

**Comment by ijt** [comment]
The debugging seems to be completely broken. I'm not sure if that is due to the use of webpack, or React, or babel, or some combination of those.

**Comment by ijt** [comment]
The debugging breakage was due to trying to debug a production deployment. Running `ion-app-web` from `npm start` has non-minified sources suitable for debugging.

It's actually `stream.publish` which the minifier had abbreviated to `t.publish`. That's a `LocalStream` object from `ion-sdk-js`, which extends `Stream` also from `ion-sdk-js`, which extends `MediaStream` (https://developer.mozilla.org/en-US/docs/Web/API/MediaStream). In Chrome, the stream has a `publish` method as defined in `LocalStream`:

<img width="880" alt="Screen Shot 2020-06-06 at 9 52 10 PM" src="https://user-images.githubusercontent.com/15530/83960665-2926bf80-a840-11ea-9d4d-380b8376bfee.png">

In Safari for some reason it is missing that method, along with some others:

<img width="692" alt="Screen Shot 2020-06-06 at 9 51 56 PM" src="https://user-images.githubusercontent.com/15530/83960667-393e9f00-a840-11ea-9e59-ea32685abcd8.png">

One possibility is that Safari does not allow subclassing `MediaStream`. @jbrady42 , what do you think?

**Comment by ijt** [comment]
I checked peer-call, which does work on Safari, and found that peer-call does not ever subclass `MediaStream`: https://github.com/peer-calls/peer-calls/search?q=mediastream&unscoped_q=mediastream.

So I am thinking that in order for ion-app-web to support Safari, it will need to use containment rather than inheritance.

**Comment by ijt** [comment]
Here's the spot to change probably: https://github.com/pion/ion-sdk-js/blob/c9cd90bad056b171740fae9104fe0a79c9cf281a/src/stream.ts#L24.

**Comment by ijt** [comment]
Something along these lines:
```typescript
export class Stream {
  static dispatch: Peer;
  static setDispatch(dispatch: Peer) {
    Stream.dispatch = dispatch;
  }

  mid?: string;
  rid?: string;
  transport?: WebRTCTransport;
  mediaStream: MediaStream;

  get dispatch(): Peer {
    if (!Stream.dispatch) {
      throw new Error('Dispatch not set.');
    }

    return Stream.dispatch;
  }
  
  // Maybe require some arguments to pass to the MediaStream.
  constructor() {
    this.mediaStream = new MediaStream();
  }
  
  // MediaStream fields and methods
  readonly active: boolean;
  readonly id: string;
  onaddtrack: ((this: MediaStream, ev: MediaStreamTrackEvent) => any) | null;
  onremovetrack: ((this: MediaStream, ev: MediaStreamTrackEvent) => any) | null;
  addTrack(track: MediaStreamTrack): void {
    this.mediaStream.addTrack(track); 
  }
  clone(): MediaStream;
  getAudioTracks(): MediaStreamTrack[];
  getTrackById(trackId: string): MediaStreamTrack | null;
  getTracks(): MediaStreamTrack[];
  getVideoTracks(): MediaStreamTrack[];
  removeTrack(track: MediaStreamTrack): void;
  addEventListener<K extends keyof MediaStreamEventMap>(type: K, listener: (this: MediaStream, ev: MediaStreamEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
  addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
  removeEventListener<K extends keyof MediaStreamEventMap>(type: K, listener: (this: MediaStream, ev: MediaStreamEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
  removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;

  // EventTarget methods
  addEventListener(type: string, listener: EventListenerOrEventListenerObject | null, options?: boolean | AddEventListenerOptions): void;
  dispatchEvent(event: Event): boolean;
  removeEventListener(type: string, callback: EventListenerOrEventListenerObject | null, options?: EventListenerOptions | boolean): void;
}
```

**Comment by greko6** [comment]
I just run into the same issue. Is there any workaround that you found? 

I cannot find solid proof, but I think Safari is not allowing to subclass GetUserMedia(). At the time of publish(), the error I see is:

TypeError: stream.publish is not a function. (In 'stream.publish(this.rid)', 'stream.publish' is undefined). [native code]

This is coming from ion-sdk-js: https://github.com/pion/ion-sdk-js/blob/c9cd90bad056b171740fae9104fe0a79c9cf281a/src/client.ts#L90 .

**Comment by greko6** [comment]
potential fix: https://github.com/pion/ion-sdk-js/pull/28

**Comment by greko6** [comment]
With that patch in place, I can stream now (which is a progress), but I don't see the remoteStream after the client.subscribe(mid).

**Comment by kevmo314** [comment]
@greko6 have you been able to get the remote stream working on Safari? I'm also running into a similar issue, namely ion doesn't work with Safari. We're using a different sdk client that's still protoo-compatible, but today I tested on ion-app-web and it doesn't render the remote stream.

I'm starting to suspect that this might be a server issue, but this might turn me away from using ion for the time being because iOS support is pretty important to us.

**Comment by kevmo314** [comment]
Also if it's helpful, the alternate sdk we've written is [ion-sdk-rxjs](https://github.com/oarli/ion-sdk-rxjs).

**Comment by ganadevprajapathy** [comment]
Is there a solution available yet? Safari doesnt show streams and fails at publishing. Current ion-sdk-js version is 0.3.9
