### ISSUE TITLE
Running with npm start fails with websocket SSL error

### ISSUE THREAD

**Issue by ijt** [pion/ion-app-web#31]
### Your environment.
  - Version: 94f6eb4b311a141422bf666a841fd24316453407
  - Browser: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

### What did you do?
```sh
cd ion
docker-compose -f docker-compose.stable.yml up
cd ../ion-app-web
npm i
npm start
```

In the browser, I entered a room name and user name.

### What did you expect?
I expected to see a video of myself and a spinner for the next guest.

### What happened?
The self video did not appear and there was a web socket error:
```
WebSocket connection to 'wss://localhost:8443/ws?peer=8024cba3-aa81-47a7-8ec9-e48c6c97d434' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
```

<img width="806" alt="Screen Shot 2020-06-06 at 6 00 24 PM" src="https://user-images.githubusercontent.com/15530/83957814-a261ea80-a81f-11ea-8d0d-91647ec0541a.png">

I worked around it by hard coding the websocket URL to `wss://ion.notmyactualdomain.live` where I have deployed ion and ion-app-web.

**Comment by tarrencev** [comment]
Should work now!
