### ISSUE TITLE
App Stuck after entering room name and display name. "Stuck at connecting"

### ISSUE THREAD

**Issue by sanjayAdhikari** [pion/ion-app-web#49]
### Your environment.
  - Version: *Release or SHA*

  - Browser: Brave Broswer
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

**Comment by aakatev** [comment]
Did you follow [these steps](https://github.com/pion/ion/blob/master/docs/dev/quick_start.md)?

**Comment by Mohamed-Gibreel** [comment]
Were you able to fix this issue ? I am currently in the same situation and cannot find a solution. Any help is appreciated !
