### ISSUE TITLE
New update of ion does not work for ion-app-web

### ISSUE THREAD

**Issue by Qolzam** [pion/ion-app-web#71]
### Your environment.
  - Version: *d1ca70f5839b0397fa4af790491e982d410013ad*
  - Browser: *Chrome Version 87.0.4280.88*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

![image](https://user-images.githubusercontent.com/8446573/101632029-dc72aa00-3a57-11eb-921e-b28321dca433.png)

 I could confirm from [new commit in ion](https://github.com/pion/ion/blob/74dcaa05c10d16d09f196d086731679436fe80cf/docker-compose.stable.yml) caused the issue. Seems `ion-app-web` is not adapted to new update in ion project.
### What did you do?

1-  In [ion](https://github.com/pion/ion) start with  `docker-compose -f docker-compose.stable.yml up -d`
2- In [ion-app-web](https://github.com/pion/ion-app-web) I used `npm start`

### What did you expect?
Websocket should be established.
### What happened?
The websocket got error `ion-conference.3f7ba6d81ab829d1566a.js:113134 WebSocket connection to 'wss://localhost:8080/ws?peer=9c5febc2-6df8-4a5b-817c-aa6aa11cbc75' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
W3CWebSocket @ ion-conference.3f7ba6d81ab829d1566a.js:113134
`

**Comment by tarrencev** [comment]
@cgojin any ideas?

**Comment by Qolzam** [comment]
FYI: I did try with new release of [ion-sdk-js](https://github.com/pion/ion-sdk-js) and it works well with new stable version of [ion docker-compose](https://github.com/pion/ion). This project is using old version of  [ion-sdk-js](https://github.com/pion/ion-sdk-js), so it should be the cause of this issue.

**Comment by tarrencev** [comment]
got it. would you mind proposing a pr to update it?

**Comment by Qolzam** [comment]
Sure! I will prepare a pull request as soon as possible.

**Comment by cgojin** [comment]
Sorry, I'm busy refactoring the ion ISLB recently, and I haven't extended ion-siganl yet. If someone does it, that's good.
