### ISSUE TITLE
Can only be accessed using localhost, not IP

### ISSUE THREAD

**Issue by javyxu** [pion/ion-app-web#81]
### Your environment.
  - macOS Big Sur 11.2.3
  - Browser:  90.0.4430.72

### What did you do?
When I use localhost or 127.0.0.1, this is fine, but when I use IP, I get the following error:
![image](https://user-images.githubusercontent.com/22185273/115492821-220c7280-a295-11eb-9979-d09fae74546e.png)
Is there any way to solve it? Thank you very much!

**Comment by adwpc** [comment]
browser policy?
