### ISSUE TITLE
ERROR in ./src/LoginForm.jsx

### ISSUE THREAD

**Issue by haiweifeng** [pion/ion-app-web#85]
I want to run project at localhost . after npm i  and i enter npm start  show this mesage.

ERROR in ./src/LoginForm.jsx
Module not found: Error: Can't resolve 'ion-sdk-js' in '/home/feng/ion-app-web/src'
 @ ./src/LoginForm.jsx 38:0-41
 @ ./src/App.jsx
 @ ./src/index.jsx

ERROR in ./src/App.jsx
Module not found: Error: Can't resolve 'ion-sdk-js/lib/ion' in '/home/feng/ion-app-web/src'
 @ ./src/App.jsx 53:0-61 105:32-44 126:34-43 130:41-50
 @ ./src/index.jsx

ERROR in ./src/Conference.jsx
Module not found: Error: Can't resolve 'ion-sdk-js/lib/ion' in '/home/feng/ion-app-web/src'
 @ ./src/Conference.jsx 21:0-49 200:18-29 256:23-34
 @ ./src/App.jsx
 @ ./src/index.jsx

**Comment by haiweifeng** [comment]
npm list | grep ion-sdk
├─┬ ion-sdk-js@1.7.0 (git://github.com/pion/ion-sdk-js.git#dfc37fa77ac20c4580f830b6431dd1cbe56b8a56)

npm v ion-sdk-js

ion-sdk-js@1.6.3 | MIT | deps: 5 | versions: 67

so i changed file package.json "ion-sdk-js":"1.6.3" and happend this error 


ERROR in ./src/App.jsx
Module not found: Error: Can't resolve 'ion-sdk-js/lib/ion' in '/home/feng/ion-app-web/src'
 @ ./src/App.jsx 53:0-61 105:32-44 126:34-43 130:41-50
 @ ./src/index.jsx

ERROR in ./src/Conference.jsx
Module not found: Error: Can't resolve 'ion-sdk-js/lib/ion' in '/home/feng/ion-app-web/src'
 @ ./src/Conference.jsx 21:0-49 200:18-29 256:23-34
 @ ./src/App.jsx
 @ ./src/index.jsx

and i do not find the file ion-app-web/src/ion-sdk-js.

**Comment by zph-dev-tech** [comment]
same erro do you solve it ?@haiweifeng
