### ISSUE TITLE
[bug]ion-app-web显示问题

### ISSUE THREAD

**Issue by long12310225** [pion/ion-app-web#91]
![image](https://user-images.githubusercontent.com/25548686/117971424-7965a600-b35c-11eb-9361-9ec6793e8fb4.png)

运行ion-app-web后，在浏览器每点击一下这个摄像机按钮，浏览器底部就会多一份对方的小画面。
![image](https://user-images.githubusercontent.com/25548686/117971699-ccd7f400-b35c-11eb-8c45-63a3a83452b0.png)

**Comment by adwpc** [comment]
Pls try new version. can reopen again
