### ISSUE TITLE
[bug]ion-app-web登陆显示问题

### ISSUE THREAD

**Issue by long12310225** [pion/ion-app-web#92]
操作：点击登录，退出，再点登录，再退出，再登录，如此类推
![image](https://user-images.githubusercontent.com/25548686/117976880-d4020080-b362-11eb-950a-984981d07be0.png)

每次登录完毕，右边的提示框越来越多，每次点击后就多一个。

![image](https://user-images.githubusercontent.com/25548686/117976724-aa48d980-b362-11eb-8e70-2e9a76ede706.png)

**Comment by adwpc** [comment]
Pls try new version. can reopen again
